### ISSUE TITLE
Autoplank not moving to the correct screen

### ISSUE THREAD

**Issue by lord-kyron** [olback/autoplank#4]
Hi again,
I didn't had time to test after the last release till today, but now I did and found some issues:
 - autoplank is now working (starting properly using the latest pre-build release) and detecting my screens, but despite it is saying switching to DP2-2 for example, it is not switching the dock sometimes. It just sayss switching and the dock stays on the same screen where it was.
 - However, when it decide to switch eventually, it is moving the dock to the screen, which is the opposite one to the one my mouse is on. For example I move my mouse on the left screen but it moves the dock on the right one. I am not sure - is it switching the dock just really slow so when I go from one monitor to the other and back it just jumps from the first to the second monitor but not again to the first. Please, take a look at this  as I think if it is not snappier moving the dock and it is not the correct monitor, it is not useful!

Thanks!

**Comment by lord-kyron** [comment]
Here is a link to a short video, to visualize what I mean:
https://streamable.com/x1lo6

As you can see sometimes it moves, sometimes it doesn't, but when it does - it is going to the opposite screen.

**Comment by olback** [comment]
Autoplank only polls your mouse location every 500ms. If you move your cursor quickly to the other monitor and then back, nothing happens. In addition to the 500ms autoplank has to restart every time you move your cursor to another monitor. 

Another problem with Elementary specifically is that there is a another process managing plank. I'll fix this is the next update.

**Comment by lord-kyron** [comment]
Ok, great! Is it possible to poll faster than that? I guess with your fix for elementary + maybe faster polling it be OK. Something like 200 ms?

**Comment by olback** [comment]
0.1.3 is out now and it has a few new features. See the [README.md](https://github.com/olback/autoplank/blob/master/README.md) for details.

If you're still having issues, please re open this issue.

**Comment by lord-kyron** [comment]
Hey this is great! So if I want to have both 200ms poll rate and elementary fix can I set it directly to Exec=.local/bin/autoplank -p 200 --elementary-fix ? Or they should be put separately?

**Comment by olback** [comment]
You only need to run `autoplank --elementary-fix` once.

**Comment by lord-kyron** [comment]
Before I set the autostart desktop service nad reboot or after that and do second reboot? Does it depends?

**Comment by olback** [comment]
Run it before you restart. If you run it before you set the desktop service or after does not matter.

**Comment by lord-kyron** [comment]
Great! Will test and give feedback! Thank you!

**Comment by lord-kyron** [comment]
Hey it is working like a charm! Thank you!
